--- Written by Ediforce44
OWN_MONSTER_ZONE_GUID = Global.getTable("ZONE_GUID_MONSTER").THREE

function onLoad()
  -- Attack button
  self.createButton({
    click_function = "dummy",
    function_owner = self,
    label          = "Attack",
    position       = {0, 1, 0},
    width          = 1000,
    height         = 300,
    font_size      = 200,
    color          = {0.2, 0.157, 0.325},
    font_color     = {1, 1, 1}
  })
end

function dummy()
end