--- Written by Ediforce44

function onLoad()
    -- Attack button
    self.createButton({
        click_function = "dummy",
        function_owner = self,
        label          = "Inactive",
        position       = {0, -0.5, 3},
        width          = 1000,
        height         = 300,
        font_size      = 200,
        color          = {0.2, 0.157, 0.325},
        font_color     = {1, 1, 1}
    })
end